apiVersion: v1
kind: Namespace
metadata:
  name: helm
  labels:
    kubernetes.io/metadata.name: helm
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: helm-project
  namespace: argocd
spec:
  description: Example Project with Helm3
  destinations:
    - name: 'PROD'
      namespace: helm
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/bettercodepaul/gitops-argocd-environment.git'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-application
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: helm
    server: 'https://kubernetes.default.svc'
  source:
    path: examples/helm/
    repoURL: 'https://github.com/bettercodepaul/gitops-argocd-environment.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  project: helm-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
