apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes
  labels:
    kubernetes.io/metadata.name: kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubernetes-project
  namespace: argocd
spec:
  description: Example Project
  destinations:
    - name: 'PROD'
      namespace: kubernetes
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/bettercodepaul/gitops-argocd-environment.git'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-application
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kubernetes
    server: 'https://kubernetes.default.svc'
  source:
    path: examples/kubernetes/
    repoURL: 'https://github.com/bettercodepaul/gitops-argocd-environment.git'
    targetRevision: HEAD
  project: kubernetes-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
