apiVersion: v1
kind: Namespace
metadata:
  name: kustomize
  labels:
    kubernetes.io/metadata.name: kustomize
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kustomize-project
  namespace: argocd
spec:
  description: Example Project with Kustomize
  destinations:
    - name: 'PROD'
      namespace: kustomize
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/bettercodepaul/gitops-argocd-environment.git'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-application
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kustomize
    server: 'https://kubernetes.default.svc'
  source:
    path: examples/kustomize/
    repoURL: 'https://github.com/bettercodepaul/gitops-argocd-environment.git'
    targetRevision: HEAD
  project: kustomize-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
